### ISSUE TITLE
The statistic chart doesn't work after w20 M3

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/i18n-function#7]
Seems like the update to w20 dataviz broke some things. The reported error:

    nv.models.multiBarChart(...).margin(...).x(...).y(...).forceY(...).width(...).height(...).showXAxis(...).showYAxis(...).showLegend(...).showControls(...).tooltips(...).reduceXTicks(...).staggerLabels(...).noData(...).rotateLabels(...).color(...).delay is not a function

**Comment by kavi87** [comment]
I'm moving this issue to w20 since it is a problem with the chart module.
